id: f3a0b28ad9be4f6988fb548175079792
title: Toh_130-The_Illusory_Absorption-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: tei
  datatype: Text
  eft-text-id: UT22084-055-004
  eft-text-version: 1.26.0 2019
  xmlns-eft: http://read.84000.co/ns/1.0
